### PR TITLE
WIP: Merging system and skeleton

### PR DESCRIPTION
**Pull request by samdoshi**
**PLEASE DON'T MERGE**

As discussed in the [Monome modular firmware on aleph][thread] thread.

I've started merging `system` and `skeleton`, just a reminder **only teletype uses system**.

So far it's just the low hanging fruit, lots of commits each with a small and hopefully atomic change. If anyone fancies reviewing the commits and making sure the changes are sane, I'd appreciate it.

I've been removing files from `system` as they've been replaced with versions from `skeleton`, so the [remaining files in system](https://github.com/samdoshi/monome-mod/tree/system-removal/system) are the ones left to merge, they are:

- [x] adc *(this is hopefully trivial too)*
- [x] i2c
- [x] init
- [x] interrupts
- [x] timers

IMO these require a bit more insight as to why the changes were made, help with these would be gladly accepted.

[thread]: http://llllllll.co/t/monome-modular-firmware-on-aleph/2475/27?u=sam

### CODE REVIEW

**Comment by samdoshi** [comment]
I've just push this https://github.com/samdoshi/monome-mod/commit/05fc4699a85eaa171c556086b37f76a86a1f22d2 to merge the i2c files. As per the commit note, I've copied the `i2c_master_tx` function from `system` into `skeleton`

**Comment by samdoshi** [comment]
Next up, `adc`.

```sh
diff -U 5 skeleton/adc.c system/adc.c
```
```diff
--- skeleton/adc.c	2015-12-23 13:05:53.000000000 +0000
+++ system/adc.c	2015-12-23 13:05:53.000000000 +0000
@@ -20,11 +20,11 @@
 #define AD7923_CTL_SEQ0   (1 << 3)
 #define AD7923_CTL_RANGE  (1 << 1)
 #define AD7923_CTL_CODING (1)

 // command word to which we add the desired channel address for conversion
-#define AD7923_CMD_BASE ( AD7923_CTL_WRITE | AD7923_CTL_PM0 | AD7923_CTL_PM1 | AD7923_CTL_CODING)
+#define AD7923_CMD_BASE ( AD7923_CTL_WRITE | AD7923_CTL_PM0 | AD7923_CTL_PM1 | AD7923_CTL_CODING | AD7923_CTL_RANGE)

 // // adc events
 // static const etype adctypes[4] = {
 //   kEventAdc0 ,
 //   kEventAdc1 ,
```

i.e. teletype adds `AD7923_CTL_RANGE`

[According to the docs][docs]:
> This bit selects the analog input range to be used on the AD7923. If it is set to 0, the analog input range extends from  0 V to 2 × REFIN. If it is set to 1, the analog input range extends from 0 V to REFIN (for the next conversion). For the 0 V to 2 × REFIN range, AVDD = 4.75 V to 5.25 V

[docs]: http://www.analog.com/media/en/technical-documentation/data-sheets/AD7923.pdf

So it's significant.

4 choices for how to deal with it:

1. Add a global variable to indicate what the range should (bit yucky IMO), set it in some init function
2. Add a new define that's device specific and use that (e.g. `#define MODULE_TRILOGY`)
3. Modify the signature for `adc_convert` to add a second argument to indicate the range. We'd have to modify all the usages of the function (only about 6 or so)
4. Similar to 3, but create 2 functions, e.g `adc_convert_5v` and `adc_convert_10v` (both can call a 3rd private function to minimise duplication)

**Thoughts?**

**Comment by samdoshi** [comment]
`timer` next!
```
diff -U 5 skeleton/timers.c system/timers.c
```
(I'm going to insert some comments into the diff)

```diff
--- skeleton/timers.c	2016-01-24 14:32:48.000000000 +0000
+++ system/timers.c	2015-12-23 13:05:53.000000000 +0000
@@ -155,12 +155,12 @@
   }

   for(i = 0; i<num; ++i) {
     --(t->ticksRemain);
     if(t->ticksRemain == 0) {
-      t->ticksRemain = t->ticks;
       (*(t->callback))(t->caller);
+      t->ticksRemain = t->ticks;
       //      print_dbg("\r\n triggered timer callback @ 0x");
       //      print_dbg_hex((u32)t);
     }
     t = t->next;
```
This change was introduced with the kria code base 6e595b11f48cff0a010eecbf2b32eab3b70dc0ec, and I don't know why or what the significance of it is. Is it a bug fix, or is it meaningless?

---

```diff
@@ -173,19 +173,13 @@
 void timer_set(softTimer_t* timer, u32 ticks) {
   timer->ticks = ticks;
   if(timer->ticksRemain > ticks) timer->ticksRemain = ticks;
 }

-void timer_reset(softTimer_t* timer, u32 ticks) {
-  timer->ticks = ticks;
-  timer->ticksRemain = ticks;
+void timer_reset(softTimer_t* timer) {
+  timer->ticksRemain = timer->ticks;
 }

-void timer_manual(softTimer_t* timer) {
+void timer_trigger(softTimer_t* timer) {
   timer->ticksRemain = 1;
 }

-
-u32 timer_ticks(softTimer_t* timer) {
-  return timer->ticksRemain;
-}
-
```
This block is pretty straightforward, the 2 sets of functions are only used in kria and teletype. I can rename and merge them easily enough.

**Comment by catfact** [comment]
re: ADC range
i don't have access to TT, so not sure the reasoning (board has different ref voltage,
but IMO this is one of the things that seems best determined at build time.

re: timers
it shouldn't matter. the only difference would be if the current softimer counter was being read by a callback. and that would be pointless because it will always read back 0 (before the change) or the reload value (after the change.)


indeed, it looks like there was added a `timer_tocks()` accessor, used only once for debugging:
https://github.com/tehn/mod/blob/master/kria/main.c#L749

i would delete this accessor since it will never give very useful values. if a callback needs the constant reload value of the timer, it should be made clearer that it *is* a contstant.

**Comment by tehn** [comment]
i can provide rationalizations when i get wifi somewhere

**Comment by samdoshi** [comment]
@tehn only if you've got time, I can wait.

**Comment by samdoshi** [comment]
`timers` done

I've removed [`timer_ticks`](https://github.com/samdoshi/monome-mod/commit/2fcb23c57e42ccf8b47b4f5e4ffdd08780122c31) and renamed a few functions

**Comment by scanner-darkly** [comment]
sorry, just getting a chance to look now. some comments on timers:

`timer_ticks` - agree with removing it since it was confusing as it returned not what you'd expect. looks like there is only one call in kria which is commented out, so would be easy to fix.

updating `ticksRemain` before doing the callback - noticed the difference too, and it makes sense to go with the skeleton version, the reason being - if for whatever reason the callback doesn't finish before the next timer, it'll do `--(t->ticksRemain);` while `ticksRemain` is still 0.

the rest makes sense!

**Comment by scanner-darkly** [comment]
re: adc `AD7923_CTL_RANGE`...

this is where i think using a mapper between the physical inputs/outputs and the app inputs/outputs would help by scaling it properly. so the app would always expect a certain 'virtual' range (unsigned word, as it is now?), and then you would have a configuration for mapper that would specify what range we expect from the physical inputs. this way you could, for instance, rebuild a firmware to expect 0..10 range instead of 0..5 without changing anything else.

for now though to make the TT and trilogy firmwares compatible i like your option #4:
_"Similar to 3, but create 2 functions, e.g adc_convert_5v and adc_convert_10v (both can call a 3rd private function to minimise duplication)"_

**Comment by samdoshi** [comment]
`init` and `interrupts` are done.

I've split:
 - `skeleton/init`
 - `system/init`
 - `skeleton/interrupts`
 - `system/interrupts`

into 3 files:
 - `skeleton/init_common`
 - `skeleton/init_teletype`
 - `skeleton/init_trilogy`

Arguably, I could have done this using a `#define`, but i decided to leave what defines we should have and where we should define them for when we merge with the aleph library. Alternatively we'll end up with an `init_aleph` file.

**Comment by samdoshi** [comment]
Right, drum roll, **adc**, the last file!

@tehn can you let me know the significance of the extra `AD7923_CTL_RANGE` on the teletype?

I've had a quick play with my teletype, the IN jack expects a voltage in of 0-10V, this makes me think the extra `AD7923_CTL_RANGE` bit is due to some hardware difference, rather than a behavioural difference, and therefore we should only have one `adc_convert` function and it should configured using a `#define`

**Comment by tehn** [comment]
there is a chance that the AD7923_CTL_RANGE is identical for both the TT
and trilogy-- a quick glance at the schems indicates they are both vref at
2.5v-- but that was a very fast glance. likely the explicit declaration
isn't needed as this is the default range, or conversely, the explicit
declaration would only clarify the range.

nothing will get damaged by testing modules with this set incorrectly-- i'd
suggest a quick test to confirm operation. apologies for an unclear answer,
it's been frustrating not having my full setup accessible, and the time to
reread the datasheet.

**Comment by samdoshi** [comment]
If I remove `AD7923_CTL_RANGE` from teletype
 - the range of `PARAM` is 0-8192 with a full turn
 - the range of `IN` is ~0-8192 with 0-10V, but it will go higher with greater than 10V

If I add `AD7923_CTL_RANGE` to earthsea, it messes with the behaviour of the knobs, they max out at 50% turn. Unfortunately I don't have a serial header so I can't debug properly.

For now I'll make it configurable with a `#define`, once you're back you can have a proper look at the schematics, if they are the same, then we'd need to fiddle with how much bitshifting each of the modules does to get a valid ADC reading.

**Comment by samdoshi** [comment]
I've just been investigating where the best place to put the `#define` for the ADC files when I noticed that the trilogy modules are all using the same `conf_board.h` file (apart from some whitespace differences), so I've moved that to `skeleton/conf/trilogy` and move the teletype one to `skeleton/conf/teletype`. It's one less file in each of the modules directories.

**Comment by samdoshi** [comment]
**No more system directory!**

A bit of testing, then we can merge?

(It's 24 commits, I could squash them down to one if anyone cares particularly.)

**Comment by scanner-darkly** [comment]
what about just defining `AD7923_CMD_BASE` in `conf_board.h`?

**Comment by samdoshi** [comment]
I thought about it, but I thought it would make `adc.c` harder to understand if `AD7923_CMD_BASE` wasn't defined there. I'm willing to change it if people think it would be better done that way.

I was also thinking there would be a `MOD_ALEPH` at some point too, and that the macros might be used in other places.

**Comment by scanner-darkly** [comment]
yeah, i agree this wouldn't be ideal. just thinking hiding hardware differences within individual files can also be confusing... ideally i think we want to share the same utility classes for aleph/tt/trilogy and have the hardware set up extracted into 1-2 files - you already made some changes towards that by refactoring `interrupts` - perhaps that's what should be done for `adc` as well?

**Comment by samdoshi** [comment]
The other option is to keep `MOD_TELETYPE` and `MOD_TRILOGY` but add the defines in the `config.mk` instead...

I think the best option might be to leave it as is for now, and then tackle the issue properly when we do the aleph merge, any solution we choose now might be invalidated by some requirement from that.

**Comment by scanner-darkly** [comment]
yep, makes sense.

**Comment by samdoshi** [comment]
I've rebased this on master and force pushed.

What's the plan? Have people had a chance to test? I've had it running on my modules, but I haven't been as in depth as I'd like.

We could just merge it and deal with any bugs that crop up as and when?

**Comment by tehn** [comment]
yes let's merge and i'll continue testing. i need to figure out this
earthsea slowdown bug.

**Comment by ngwese** [comment]
I'm trying to rebase my ```es-midi``` branch on top of the unified skeleton and there is one conflict I'm sure how best to handle:
https://github.com/ngwese/mod/blob/feature/es-midi/skeleton/conf/conf_usb_host.h#L14-L22

I can certainly change this to #ifdef MOD_TELETYPE and #ifdef MOD_TRILOGY (since that seems like where the dust settled for the moment). What I'm less sure of is whether there is any harm in enabling UHI_MIDI across the entire trilogy - I don't remember off the top of my head whether handlers need to be defined in order to prevent the modules from locking up if a midi devices was plugged in....

Apologies for not digging in and figuring this out before asking (work is capitalizing on all my time right now).

**Comment by ngwese** [comment]
+1 for moving MOD_TELETYPE and MOD_TRILOGY to ```config.mk``` in for each of the individual module directories. I did nearly the same thing when fiddling with the things a fea months back:
https://github.com/ngwese/mod/blob/feature/es-midi/earthsea/config.mk#L180

I do wonder what the right balance is between having lots of conditional bits in common code versus factoring out those same bits into each module directory. I guess the answer depends on whether the logic needs to be customized for each and every module versus one or two. ...not sure where the USB_HOST_UHI definition lands on that spectrum.

**Comment by samdoshi** [comment]
As far as I know you can add the extra `UHI_MIDI` to `USB_HOST_UHI`, it does end up increasing the ROM size a little bit though. Maybe do a quick test? I'll try and have a go myself later this week, if the lack of handlers is a problem, I guess we could add some null op ones.

Anyway, I think the MIDI code you've added would be really useful on all the modules, perhaps in a way that's sympathetic to the firmware, WW could be a 2 channel converter, MP a MIDI clock divider. I know @tehn is planning on adding MIDI triggering of scripts to teletype, so arguably you could change the `USB_HOST_UHI` for everything.

On the subject of where to put the conditionals... I'm pretty easy, I thought it would be best to just get something done, so I kinda picked a solution at random. I'm still of the opinion that we need to decide what we're trying to achieve (sharing code with Aleph, multiple apps on a module, etc) before making too many code decisions. Maybe in a week or 2 I'll post something on the lines thread to prod people into giving it some thought.

**Comment by tehn** [comment]
adding UHI_MIDI to all shouldn't be a problem, and yes, i'm excited to get
some MIDI into teletype (grids as well).

i'll test now...

**Comment by tehn** [comment]
done and all modules tested.

**Comment by scanner-darkly** [comment]
+1 for adding UHI_MIDI, i agree it would be very useful for all modules.

**Pull request merged**
